# Generated by Django 3.2.7 on 2021-09-06 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210906_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 14, 12, 15, 676354), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
